# Site settings
title: ZML Blog
SEOTitle: mlzhong的摸鱼志 | ZML Blog
header-img: img/post-bg-desk.jpg
email: 446864360@qq.com
description: "啥都没有啦，你可以随便看看 /笔端有风月"
keyword: "mlzhong, ZML, ZML Blog, 摸鱼志, zhongminling, 钟敏玲, "
url: "https://mlzhong.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/mlzhong/mlzhong.github.io.git" # you code repository



# SNS settings
RSS: false
weibo_username:    
#zhihu_username:     huxpro
github_username:    mlzhong
#twitter_username:  huxpro
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: wengdada
#disqus_share: true


# Duoshuo settings
#duoshuo_username: wengdada
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: '64436c0e2440da0973ca'    #生成的clientID
  clientSecret: '3b2314886e6b6690b9931d1c5081c1be22ca2c6a'   #同上
  repo: mlzhong.github.io    #仓库名称
  owner: mlzhong    #github用户名
  admin: mlzhong
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计
# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "茶或酒 饮与酌 梅雪落作杯中色"
sidebar-avatar: /img/about-BY-gentle.jpg       # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                    # 是否使用首页标签
featured-condition-size: 0             # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# # Friends
# friends: [
#     {
#         title: "Su",
#         href: "http://su.gallery/"
#     },{
#         title: "前端神盾局",
#         href: "http://wepiaofei.github.io/blog/"
#     }
#     ,{
#         title: "Android Developer",
#         href: "https://developer.android.google.cn/index.html"
#     }
# ]
